version: "3.9"

services:
  jenkins-application:
    build:
      context: .
      dockerfile: Dockerfile.jenkins.k8s
    container_name: jenkins-application
    privileged: true
    user: root
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - "C:/k8s/kind-config.yaml:/var/jenkins_home/.kube/config"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:

networks:
  default:
